language: cpp

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

cache: apt

notifications:
  slack: dgtal:FObxCZFoeQkkaRuktJD5uhnN

########
# matrix details:
#    - one build for the documentation on macosx (clang) and only for commits on
#      DGtal-team repo (no pull request). Encrypted var. required.
#    - No gcc on macosx
#    - Otherwise, 2 os x 2 configs
#
########
env:
  - CONFIG="Debug,Magick,GMP,ITK"
  - CONFIG="Debug,Cairo,QGLviewer,HDF5"
  - CONFIG="Documentation,Debug,Cairo,GMP"

matrix:
  fast_finish: true 
  exclude:
    - os: linux
      env: CONFIG="Documentation,Debug,Cairo,GMP"
    - compiler: gcc
      os: osx
      env: CONFIG="Documentation,Debug,Cairo,GMP"
    - os: osx
      compiler: gcc

addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - libhdf5-serial-dev
    - libboost-dev
    - libcairo2-dev
    - doxygen
    - doxygen-latex
    - graphviz
    - libboost-system-dev
    - libgmp-dev
    - libgdcm2-dev 
    - libgraphicsmagick++1-dev
    - libqglviewer-qt4-dev
    - libinsighttoolkit3-dev
    - g++-4.8
    - gcc-4.8
    

before_install:
  - if [ $CXX == "g++" ]; then CCOMPILER="gcc-4.8"; CXXCOMPILER="g++-4.8"; fi
  - DOC="false"
  - NEEDBUILD="true";
  - if [ $CONFIG == "Documentation,Debug,Cairo,GMP" ]; then NEEDBUILD="false"; if [ $OriginalRepo == "true" ];  then if [ $TRAVIS_PULL_REQUEST == "false" ]; then DOC="true"; fi; fi; fi
  - if [ $CONFIG == "Debug,Magick,GMP,ITK" ]; then BTYPE="-DCMAKE_BUILD_TYPE=Debug  -DWITH_MAGICK=true -DWITH_GMP=true  -DBUILD_TESTING=ON  -DWARNING_AS_ERROR=ON";  fi
  - if [ $CONFIG == "Debug,Cairo,QGLviewer,HDF5" ]; then BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_HDF5=true -DWITH_CAIRO=true -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON -DWARNING_AS_ERROR=OFF";   fi
  - if [ $DOC == "true" ]; then  BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true  -DWITH_GMP=true"; DOC="true"; openssl aes-256-cbc -K $encrypted_47769ec71275_key -iv $encrypted_47769ec71275_iv -in .travis/dgtal_rsa.enc -out .travis/dgtal_rsa -d; chmod 600 .travis/dgtal_rsa; DOC="true"; fi


########
# Deps.
########
before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then echo "All done.";   fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew install boost doxygen homebrew/science/hdf5 graphviz graphicsmagick  gmp libqglviewer; echo "done";fi


############
# Main rules
############
script:
  - cmake . $BTYPE -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER
  - echo $DOC
  - echo $BTYPE
  - if [ $NEEDBUILD == "true" ]; then  make DGtal && make DGtalIO; fi
  - if [ $NEEDBUILD == "true" ]; then  cd examples && make  -j 3 ; fi
  - if [ $NEEDBUILD == "true" ]; then  cd ../tests &&  make -j 3 &&  cd .. ; fi
  - if [ $NEEDBUILD == "true" ]; then  make test;  fi

###########
## Building the documentation
###########
after_success:
  - if [ $DOC == "true" ]; then  make doc; fi
  - if [ $DOC == "true" ]; then rsync -azv --delete --delete-after -e 'ssh -oStrictHostKeyChecking=no -i  .travis/dgtal_rsa' html/ dgtal@liris.cnrs.fr:/home/dgtal/public_html/doc/nightly/;  fi
  - if [ $DOC == "true" ]; then cd html; make ; wget http://dgtal.org/doc/docset/template.tgz ; tar zxvf template.tgz ; mv template/* org.dgtal.docset ; tar zcvf DGtal-devel.tgz org.dgtal.docset ; cd .. ;rsync  -azv --delete --delete-after -e 'ssh -oStrictHostKeyChecking=no -i  .travis/dgtal_rsa' html/DGtal-devel.tgz dgtal@liris.cnrs.fr:/home/dgtal/public_html/doc/docset ;   fi
  - echo "All done..."
